name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Lint:

  UnitTest:
    # runner env
    runs-on: ubuntu-latest
    # steps
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test - lazy-load
        run: cd packages/lazy-load && pnpm run test:run
      - name: Run Test - seamless-scroll
        run: cd packages/seamless-scroll && pnpm run test:run
      - name: Run Test - table
        run: cd packages/table && pnpm run test:run
      - name: Run Test - pdf
        run: cd packages/pdf && pnpm run test:run
