name: Publish Package
on:
  push:
    branches: [main]
jobs:
  # install 测试环境
  check-package-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: install dependencies
        run: pnpm install
      - name: publish - lazy-load
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/lazy-load/package.json
