name: Publish Package
on:
  push:
    branches: [main]
jobs:
  # install 测试环境
  check-package-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: install dependencies
        run: pnpm install
  publish-layz-load:
    runs-on: ubuntu-latest
    needs: check-package-change
    steps:
      - name: Install dependencies
        run: cd ./packages/lazy-load && pnpm install
      - name: build
        run: cd ./packages/lazy-load && pnpm build
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/lazy-load/package.json
  publish-seamless-scroll:
    runs-on: ubuntu-latest
    needs: check-package-change
    steps:
      - name: Install dependencies
        run: cd ./packages/seamless-scroll && pnpm install
      - name: build
        run: cd ./packages/seamless-scroll && pnpm build
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/seamless-scroll/package.json
  publish-table:
    runs-on: ubuntu-latest
    needs: check-package-change
    steps:
      - name: Install dependencies
        run: cd ./packages/table && pnpm install
      - name: build
        run: cd ./packages/table && pnpm build
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/table/package.json
