name: Publish Package
on:
  push:
    branches: [main]
jobs:
  # install 测试环境
  check-package-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: install dependencies
        run: pnpm install
      # 怎么依赖上一个job的环境，
      # lazy-load
      - name: publish-layz-load
        run: cd packages/lazy-load && pnpm install
        run: cd packages/lazy-load && pnpm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/lazy-load/package.json
      # seamless-scroll
      - name: publish-seamless-scroll
        run: cd packages/seamless-scroll && pnpm install
        run: cd packages/seamless-scroll && pnpm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/seamless-scroll/package.json
      # table
      - name:  publish-table
        run: cd packages/table && pnpm install
        run: cd packages/table && pnpm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./packages/table/package.json
